{
 "title": "Resource Requests / Total Resources By Namespace",
 "tags": [
  "kubernetes",
  "requests"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Cpu Requests By Namespace",
   "type": "piechart",
   "description": "cpu requests / total cluster cpu by namespace",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (namespace) (eagle_pod_container_resource_requests_cpu_cores{phase=\"Running\"}) / ignoring(namespace) group_left sum(eagle_node_resource_allocatable_cpu_cores)) * 100"
    }
   ]
  },
  {
   "title": "Memory Requests By Namespace",
   "type": "piechart",
   "description": "memory requests / total cluster cpu by namespace",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (namespace) (eagle_pod_container_resource_requests_memory_bytes{phase=\"Running\"}) / ignoring(namespace) group_left sum(eagle_node_resource_allocatable_memory_bytes)) * 100\n"
    }
   ]
  },
  {
   "title": "Weekly Cpu Summation",
   "type": "piechart",
   "description": "week summation of: cpu requests / total cluster cpu by namespace",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(sum_over_time(eagle_pod_container_resource_requests_cpu_cores{namespace=~\".+\", phase=\"Running\"}[7d])) by (namespace) / ignoring(namespace) group_left sum(sum_over_time(eagle_node_resource_allocatable_cpu_cores[7d]))) * 100"
    }
   ]
  },
  {
   "title": "Weekly Memory Summation",
   "type": "piechart",
   "description": "week summation of: memory requests / total cluster memory by namespace",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(sum_over_time(eagle_pod_container_resource_requests_memory_bytes{namespace=~\".+\", phase=\"Running\"}[7d])) by (namespace) / ignoring(namespace) group_left sum(sum_over_time(eagle_node_resource_allocatable_memory_bytes[7d]))) * 100\n"
    }
   ]
  }
 ]
}